# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='projects/img'),
        ),
    ]
