# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170402_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
