# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170104_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
