# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170402_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='toto'),
        ),
    ]
